# Generated by Django 4.0.4 on 2022-06-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('testimonial', models.TextField()),
            ],
        ),
    ]
